export { ContactInfo } from './ContactInfo'
export { Education } from './Education'
export { Experience } from './Experience'
export { Languages } from './Languages'
export { Skills } from './Skills'
